background {
    path = $HOME/.cache/awww/normal.png
    blur_passes = 3
    blur_size = 6
}

input-field {
    size = 200, 30
    outline_thickness = 2
    dots_size = 0.3
    dots_center = true
    inner_color = rgb(1e1e2e)
    font_color = rgb(cdd6f4)
    outline_color = rgb(89b4fa)
    hide_input = false
    rounding = 8
    check_color = rgb(a6e3a1)
    fail_color = rgb(f38ba8)
    position = 0, -20
    halign = center
    valign = center
    placeholder_text = <i>Input Password</i>
    fail_text = <i>$FAIL</i>
}

label {
    text = cmd[update:1000] echo "$TIME"
    color = rgb(cdd6f4)
    font_size = 100
    font_family = JetBrainsMono Nerd Font
    position = 0, 150
    halign = center
    valign = center
    shadow_passes = 5
    shadow_size = 10
}
