#   ░▒▓████████▓▒░  ░▒▓█▓▒░░░░▒▓█▓▒░  ░▒▓███████████▓▒░  ░▒▓█████████▓▒░  ░▒▓█████████▓▒░  ░▒▓███████████▓▒░  ░▒▓████████▓▒░  ░▒▓███████▓▒░  ░▒▓███████████▓▒░
#   ░▒▓█▓▒░░▒▓█▓▒░  ░▒▓█▓▒░░░░▒▓█▓▒░         ░▒▓█▓▒░  ░▒▓█▓▒░░░░▒▓█▓▒░  ░▒▓█▓▒░         ░▒▓█▓▒░  ░▒▓█▓▒░░▒▓█▓▒░  ░▒▓█▓▒░░▒▓█▓▒░         ░▒▓█▓▒░
#   ░▒▓█▓▒░░▒▓█▓▒░  ░▒▓█▓▒░░░░▒▓█▓▒░         ░▒▓█▓▒░  ░▒▓█▓▒░░░░▒▓█▓▒░  ░▒▓█▓▒░         ░▒▓█▓▒░  ░▒▓█▓▒░░▒▓█▓▒░  ░▒▓█▓▒░░▒▓█▓▒░         ░▒▓█▓▒░
#   ░▒▓████████▓▒░  ░▒▓█▓▒░░░░▒▓█▓▒░         ░▒▓█▓▒░  ░▒▓█▓▒░░░░▒▓█▓▒░  ░▒▓█████████▓▒░         ░▒▓█▓▒░  ░▒▓████████▓▒░  ░▒▓███████▓▒░         ░▒▓█▓▒░
#   ░▒▓█▓▒░░▒▓█▓▒░  ░▒▓█▓▒░░░░▒▓█▓▒░         ░▒▓█▓▒░  ░▒▓█▓▒░░░░▒▓█▓▒░           ░▒▓█▓▒░         ░▒▓█▓▒░  ░▒▓█▓▒░░▒▓█▓▒░  ░▒▓█▓▒░░▒▓█▓▒░         ░▒▓█▓▒░
#   ░▒▓█▓▒░░▒▓█▓▒░  ░▒▓██████████▓▒░         ░▒▓█▓▒░  ░▒▓█████████▓▒░  ░▒▓█████████▓▒░         ░▒▓█▓▒░  ░▒▓█▓▒░░▒▓█▓▒░  ░▒▓█▓▒░░▒▓█▓▒░         ░▒▓█▓▒░
#------------------------------------------------------------------------------------------------



exec-once = waybar
exec-once = swaync
exec-once = awww-daemon && sleep 0.5 && awww img "$(find ~/Pictures/Wallpapers -maxdepth 1 -type f | shuf -n 1)" --transition-type any --transition-duration 2
exec-once = hypridle
exec-once = nm-applet --indicator

# Setup fcitx5
exec-once = fcitx5

# Setup screen sharing
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Setup clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Setup themes
exec-once = ~/.config/viegphunt/gtkthemes.sh